STREAMING_CHUNK:Setting up base Python image...
​FROM python:3.11-slim
​STREAMING_CHUNK:Configuring working directory...
​WORKDIR /app
​STREAMING_CHUNK:Installing required packages...
​COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
​STREAMING_CHUNK:Copying project files and starting app...
​COPY . .
​EXPOSE 8080
​CMD ["python", "app.py"]
